framework/flask/zhiliao/models.py
from datetime import datetime

from ext import db

class EmailCaptchaModel(db.Model):
    __tablename__ = "email_captcha"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    email = db.Column(db.String(100), nullable=False, unique=True)
    captcha = db.Column(db.String(100), nullable=False)
    create_time = db.Column(db.DateTime, default=datetime.now())

class UserModel(db.Model):
    __tablename__ = "user"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(200), nullable=False, unique=True)
    password = db.Column(db.String(200), nullable=False)
    email = db.Column(db.String(100), nullable=False, unique=True)
    join_time = db.Column(db.DateTime, default=datetime.now())
class QuestionModel(db.Model):
    __tablename__ = "question"
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    title = db.Column(db.String(200), nullable=False)
    content = db.Column(db.Text, nullable=False)
    author_id = db.Column(db.Integer,db.ForeignKey("user.id"))

    author = db.relationship("UserModel", backref="questions")

framework/flask/zhiliao/blueprints/forms.py
import wtforms
from wtforms.validators import length, email, EqualTo
from models import EmailCaptchaModel, UserModel


class RegisterForm(wtforms.Form):
    username = wtforms.StringField(validators=[length(min=3, max=20)])
    captcha = wtforms.StringField(validators=[length(min=4, max=4)])
    password = wtforms.StringField(validators=[length(min=6, max=20)])
    password_confirm = wtforms.StringField(validators=[EqualTo("password")])
    email = wtforms.StringField(validators=[email()])

    def validate_captcha(self, field):
        captcha = field.data
        email = self.email.data
        captcha_model = EmailCaptchaModel.query.filter_by(email=email).first()
        if not captcha_model or captcha_model.captcha.lower() != captcha.lower():
            raise wtforms.ValidationError("email valification code error.")

    def validate_email(self, field):
        email = field.data
        user_model = UserModel.query.filter_by(email=email).first()
        if user_model:
            raise wtforms.ValidationError("email already exist.")


class LoginForm(wtforms.Form):
    email = wtforms.StringField(validators=[email()])
    password = wtforms.StringField(validators=[length(min=6, max=20)])


class QuestionForm(wtforms.Form):
    title = wtforms.StringField(validators=[length(min=3, max=20)])
    content = wtforms.StringField(validators=[length(min=3)])

framework/flask/zhiliao/app.py
from flask import Flask, session, g
import config
from ext import db, mail
from blueprints import qa_bp
from blueprints import user_bp
from flask_migrate import Migrate
from models import UserModel

# from https://www.zlkt.net/book/detail/10/273
app = Flask(__name__)
app.config.from_object(config)
db.init_app(app)
mail.init_app(app)

migrate = Migrate(app, db)

app.register_blueprint(qa_bp)
app.register_blueprint(user_bp)


@app.before_request
def before_request():
    user_id = session.get("user_id")
    if user_id:
        try:
            user = UserModel.query.get(user_id)
            # setattr(g, "user", user)
            g.user = user
        except:
            pass

@app.context_processor
def context_processor():
    if hasattr(g,"user"):
        return {"user": g.user}
    else:
        return {}

if __name__ == '__main__':
    app.run()

framework/flask/zhiliao/blueprints/__init__.py
from .qa import bp as qa_bp
from .user import bp as user_bp

framework/flask/zhiliao/blueprints/qa.py
from flask import Blueprint, render_template, g, request, redirect, url_for, flash
from decorators import login_requested
from .forms import QuestionForm
from ext import db
from models import QuestionModel

bp = Blueprint("qa", __name__, url_prefix="/")


@bp.route("/")
def index():
    questions = QuestionModel.query.all()
    return render_template('index.html', questions=questions)


@bp.route("/question/public", methods=["GET", "POST"])
@login_requested
def public_question():
    if request.method == "GET":
        return render_template('public_question.html')
    else:
        form = QuestionForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            question = QuestionModel(title=title, content=content, author=g.user)
            db.session.add(question)
            db.session.commit()
            return redirect("/")
        else:
            flash("标题或者内容格式错误！")
            return redirect(url_for("qa.public_question"))

framework/flask/zhiliao/blueprints/user.py
from flask import Blueprint, render_template, request, redirect, url_for, jsonify, session, flash
from ext import mail, db
from flask_mail import Message
from models import EmailCaptchaModel, UserModel
from datetime import datetime
import string, random
from .forms import RegisterForm, LoginForm
from werkzeug.security import generate_password_hash, check_password_hash

bp = Blueprint("user", __name__, url_prefix="/user")


@bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "GET":
        return render_template("login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = UserModel.query.filter_by(email=email).first()
            if user and check_password_hash(user.password, password):
                session['user_id'] = user.id
                return redirect("/")
            else:
                flash("邮箱和密码不匹配")
                return redirect(url_for("user.login"))
        else:
            flash("邮箱格式错误")
            return redirect(url_for("user.login"))


@bp.route("/register", methods=["GET", "POST"])
def register():
    if request.method == "GET":
        return render_template("register.html")
    else:
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.captcha.data
            password = form.password.data
            hash_password = generate_password_hash(password)
            user = UserModel(email=email, username=username, password=hash_password)
            db.session.add(user)
            db.session.commit()
            return redirect(url_for("user.login"))
        else:
            return redirect(url_for("user.register"))

@bp.route("/logout")
def logout():
    session.clear()
    return redirect(url_for('user.login'))

@bp.route("/captcha", methods=["POST"])
def get_captcha():
    email = request.form.get("email")
    if email:
        letters = string.ascii_letters + string.digits
        captcha = "".join(random.sample(letters, 4))
        # message = Message(
        #     subject="邮箱测试",
        #     recipients=[email],
        #     body=f"your code is {captcha}",
        # )
        # mail.send(message)
        captcha_model = EmailCaptchaModel.query.filter_by(email=email).first()
        if captcha_model:
            captcha_model.captcha = captcha
            captcha_model.create_time = datetime.now()
            db.session.commit()
        else:
            captcha_model = EmailCaptchaModel(email=email, captcha=captcha)
            db.session.add(captcha_model)
            db.session.commit()
        return jsonify({"code": 200})
    else:
        return jsonify({"code": 400, "message": "need email"})

framework/flask/zhiliao/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
我们是 {{ username }}
</body>
</html>

framework/flask/zhiliao/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/bootstrap@5.1.3.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/init.css') }}">
  {% block head %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">知了问答</a>
      <button class="navbar-toggler" type="button" data-bs-toggccccccccccccccccccccccccccccccccccccccle="collapse"
              data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
              aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">首页</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('qa.public_question') }}">发布问答</a>
          </li>
          <li class="nav-item  m-lg-2">
            <form class="d-flex">
              <input class="form-control me-2" type="search" placeholder="关键字" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">搜索</button>
            </form>
          </li>
        </ul>

      </div>

    </div>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav">
        {% if user %}
          <li class="nav-item">
            <a class="nav-link">{{ user.username }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.logout')}}">退出登录</a>
          </li>
        {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.login') }}">登录</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.register') }}">注册</a>
          </li>
        {% endif %}

      </ul>

    </div>
  </div>
</nav>
<div class="container">
  {% block body %}{% endblock %}
</div>
</body>
</html>

framework/flask/zhiliao/templates/index.html
{% extends "base.html" %}

{% block Title %}
  知了问答 - 首页
{% endblock %}

{% block head %}
{% endblock %}

{% block body %}
  <div class="row">
    <div class="col"></div>
    <div class="col-8">
      <ul>
        {% for question in questions %}
          <li>
          <div> here is a image</div>
          <div>
            <div>{{ question.title }}</div>
            <div>{{ question.content }}</div>
            <div>{{ question.author.username }}</div>
          </div>
          </li>
        {% endfor %}
      </ul>
    </div>
    <div class="col"></div>

  </div>
{% endblock %}

framework/flask/zhiliao/templates/login.html
{% extends "base.html" %}

{% block Title %}
  知了问答 - 登录
{% endblock %}

{% block head %}
{% endblock %}

{% block body %}


  <div class="row mt-5">
    <div class="col">
    </div>
    <div class="col">
      <form action="{{ url_for("user.login") }}" method="POST">
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">邮箱</label>
          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">密码</label>
          <input type="password" class="form-control" id="exampleInputPassword1" name="password">
        </div>
        {% for message in get_flashed_messages() %}
          <div class="text-danger">{{ message }}</div>
        {% endfor %}
        <div class="d-grid gap-2">
          <button type="submit" class="btn btn-primary">立即登录</button>
        </div>
      </form>
    </div>
    <div class="col">
    </div>
  </div>

{% endblock %}

framework/flask/zhiliao/templates/public_question.html
{% extends "base.html" %}
{% block title %}
  发布问答
{% endblock %}

{% block body %}
  <div class="row" style="margin-top: 20px;">
    <div class="col"></div>


    <div class="col-8">
      <h1 style="text-align: center">发布问答</h1>
      <form method="post" action="{{ url_for('qa.public_question') }}">
        <div class="form-group">
          <input type="text" name="title" placeholder="请输入标题" class="form-control">
        </div>
        <div class="form-group">
          <textarea name="content" class="form-control" rows="10" placeholder="请输入内容"></textarea>
        </div>
        {% for message in get_flashed_messages() %}
          <div class="text-danger">{{ message }}</div>
        {% endfor %}
        <div class="form-group" style="text-align: right">
          <button class="btn btn-primary">发布</button>
        </div>
      </form>

    </div>
    <div class="col"></div>


  </div>
{% endblock %}

framework/flask/zhiliao/templates/register.html
{% extends "base.html" %}

{% block Title %}
  知了问答 - 注册
{% endblock %}

{% block head %}
  <script src="{{ url_for('static', filename='jquery/jquery.3.6.min.js') }}"></script>
  <script src="{{ url_for('static', filename='js/register.js') }}"></script>
{% endblock %}

{% block body %}
  <div class="row mt-5">
    <div class="col">
    </div>
    <div class="col">
      <form method="post" action="{{ url_for('user.register') }}"  >
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">邮箱</label>
          <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" name="email">
          <div id="emailHelp" class="form-text">我们不会把邮箱用于其他用途.</div>
        </div>
        <div class="input-group mb-3">
          <input type="text" class="form-control" placeholder="请输入验证码" aria-label="Recipient's username"
                 aria-describedby="button-addon2" name="captcha">
          <button class="btn btn-outline-secondary" type="button" id="button-addon2">获取验证码</button>
        </div>
                <div class="mb-3">
          <label for="username" class="form-label">用户名</label>
          <input type="text" class="form-control" id="username" aria-describedby="emailHelp" name="username">
          <div id="emailHelp" class="form-text">我们不会把邮箱用于其他用途.</div>
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">密码</label>
          <input type="password" class="form-control" id="exampleInputPassword1" name="password">
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword2" class="form-label">确认密码</label>
          <input type="password" class="form-control" id="exampleInputPassword2" name="password_confirm">
        </div>
        <div class="d-grid gap-2">
          <button type="submit" class="btn btn-primary">立即注册</button>
        </div>
      </form>
    </div>
    <div class="col">
    </div>
  </div>
{% endblock %}